name: Tests

on:
  push:

jobs:
  system_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-31

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install and Run Appium Server
        run: |
          chmod +x ./runAppium.sh # install and run appium server in the background
          ./runAppium.sh

      - name: Grant execute permissions to Gradle
        run: chmod +x ./gradlew

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: 31
          arch: x86_64
          profile: pixel
          script: ./gradlew clean test
